# Generated by Django 3.2.8 on 2021-10-29 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('creci', models.CharField(max_length=200)),
                ('dtanasc', models.DateField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estadoconser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomecondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, db_column='UF', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Padrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabelarossheideck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_em_de_vida', models.TextField(blank=True, db_column='IDADE EM % DE VIDA', null=True)),
                ('a', models.TextField(blank=True, db_column='A', null=True)),
                ('b', models.TextField(blank=True, db_column='B', null=True)),
                ('c', models.TextField(blank=True, db_column='C', null=True)),
                ('d', models.TextField(blank=True, db_column='D', null=True)),
                ('e', models.TextField(blank=True, db_column='E', null=True)),
                ('f', models.TextField(blank=True, db_column='F', null=True)),
                ('g', models.TextField(blank=True, db_column='G', null=True)),
                ('h', models.TextField(blank=True, db_column='H', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vidautil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('idadevidautil', models.IntegerField(blank=True, db_column='idadeVidaUtil', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valordevenda', models.DecimalField(blank=True, db_column='valorDeVenda', decimal_places=2, max_digits=10, null=True, verbose_name='Valor de venda')),
                ('idade', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=200)),
                ('aconstruida', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Área Construída/Útil')),
                ('atotal', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Área Total')),
                ('dtacadastro', models.DateField(blank=True, db_column='dtaCadastro', null=True, verbose_name='Data de cadastro')),
                ('status', models.IntegerField(verbose_name='Estatus')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.corretor')),
                ('estadoconser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.estadoconser', verbose_name='Estado de Conservação')),
                ('nomecondominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.nomecondominio', verbose_name='Condominio')),
                ('padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.padrao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tipo')),
                ('vidautil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.vidautil', verbose_name='Vida Útil')),
            ],
        ),
    ]
