# Generated by Django 3.2.8 on 2021-10-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='aconstruida',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área Construída/Útil'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='atotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Total'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[(1, 'Oferta'), (2, 'Vendido')], max_length=1, verbose_name='Estatus'),
        ),
    ]
