# Generated by Django 4.0b1 on 2021-11-09 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20211031_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='aconstruida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Área Construída/Útil'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='corretor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.corretor'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='estadoconser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.estadoconser', verbose_name='Estado de Conservação'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='idade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='padrao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.padrao'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('1', 'Oferta'), ('2', 'Vendido')], max_length=1),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.tipo'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vidautil',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.vidautil', verbose_name='Vida Útil'),
        ),
        migrations.AlterUniqueTogether(
            name='imovel',
            unique_together={('padrao', 'tipo', 'nomecondominio', 'estadoconser', 'corretor', 'vidautil')},
        ),
    ]
