# Generated by Django 4.0b1 on 2021-11-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_imovel_aconstruida_alter_imovel_bairro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomecondominio',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='imovel',
            name='aconstruida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área Construída/Útil'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='atotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área Total'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valordevenda',
            field=models.DecimalField(db_column='valorDeVenda', decimal_places=2, default=0, max_digits=10, verbose_name='Valor de venda'),
        ),
    ]
