# Generated by Django 4.0b1 on 2021-11-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_nomecondominio_options_alter_tipo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelarossheideck',
            name='idade_em_de_vida',
            field=models.TextField(blank=True, db_column='idade_perc_vida', null=True),
        ),
    ]
