# Generated by Django 4.0b1 on 2021-11-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_tabelarossheideck_idade_em_de_vida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelarossheideck',
            name='idade_em_de_vida',
            field=models.TextField(blank=True, db_column='idade_em_de_vida', null=True),
        ),
    ]
