# Generated by Django 4.0b1 on 2021-11-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_tabelarossheideck_idade_em_de_vida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelarossheideck',
            name='a',
        ),
        migrations.RemoveField(
            model_name='tabelarossheideck',
            name='b',
        ),
        migrations.RemoveField(
            model_name='tabelarossheideck',
            name='c',
        ),
        migrations.RemoveField(
            model_name='tabelarossheideck',
            name='d',
        ),
        migrations.RemoveField(
            model_name='tabelarossheideck',
            name='e',
        ),
        migrations.RemoveField(
            model_name='tabelarossheideck',
            name='f',
        ),
        migrations.RemoveField(
            model_name='tabelarossheideck',
            name='g',
        ),
        migrations.RemoveField(
            model_name='tabelarossheideck',
            name='h',
        ),
        migrations.AddField(
            model_name='tabelarossheideck',
            name='A',
            field=models.TextField(blank=True, db_column='A', null=True),
        ),
        migrations.AddField(
            model_name='tabelarossheideck',
            name='B',
            field=models.TextField(blank=True, db_column='B', null=True),
        ),
        migrations.AddField(
            model_name='tabelarossheideck',
            name='C',
            field=models.TextField(blank=True, db_column='C', null=True),
        ),
        migrations.AddField(
            model_name='tabelarossheideck',
            name='D',
            field=models.TextField(blank=True, db_column='D', null=True),
        ),
        migrations.AddField(
            model_name='tabelarossheideck',
            name='E',
            field=models.TextField(blank=True, db_column='E', null=True),
        ),
        migrations.AddField(
            model_name='tabelarossheideck',
            name='F',
            field=models.TextField(blank=True, db_column='F', null=True),
        ),
        migrations.AddField(
            model_name='tabelarossheideck',
            name='G',
            field=models.TextField(blank=True, db_column='G', null=True),
        ),
        migrations.AddField(
            model_name='tabelarossheideck',
            name='H',
            field=models.TextField(blank=True, db_column='H', null=True),
        ),
        migrations.AlterField(
            model_name='tabelarossheideck',
            name='idade_em_de_vida',
            field=models.TextField(blank=True, db_column='idade_em_de_vida ', null=True),
        ),
    ]
